apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: helloworld-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
